name: 'Setup Dependencies'
description: “Setup Node, install cypress binaries, cache cypress binaries + node_modules”

inputs:
  node-version:
    description: 'The Node.js version to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - uses: pnpm/action-setup@v4
      name: Install pnpm

    - name: Cache apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb

    - name: Cache Cypress binary
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/Cypress
        key: cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          cypress-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Ensure Cypress binary is installed
      shell: bash
      run: pnpm exec cypress install
