export default function lorem() {
  return (
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas massa a nunc feugiat faucibus ut quis justo. Pellentesque tempus vitae turpis ut fermentum. Mauris sodales neque ipsum, ut dapibus urna posuere nec. Cras facilisis diam non augue tempor commodo. Sed hendrerit rhoncus arcu, non dictum turpis mattis eget. In ut elit lorem. Quisque eu nulla non ligula mollis sollicitudin. Integer a erat a ligula commodo congue. Phasellus eros lorem, vulputate sit amet efficitur eu, posuere nec arcu. Duis ullamcorper ante diam, non aliquam lorem porttitor in.' +
    '\n' +
    'Fusce imperdiet, tellus eget viverra hendrerit, ipsum orci vulputate erat, at ultricies massa lectus vitae diam. Sed aliquet vulputate cursus. Curabitur orci ex, maximus vitae ultricies in, feugiat ut massa. Ut at sapien et turpis imperdiet porttitor vel vitae dolor. Quisque ut laoreet enim, eget facilisis massa. In dapibus lectus dui, id vestibulum quam laoreet in. Vivamus at ipsum et dolor faucibus finibus. Integer id mattis dui.' +
    '\n' +
    'Maecenas porttitor mattis lorem, ac scelerisque dolor condimentum at. Nunc nec elit sed ex ullamcorper aliquam eu sed sem. Vivamus aliquam ut tortor a tincidunt. Cras bibendum, velit vel consequat accumsan, est urna finibus dui, ac varius magna neque eget eros. Nulla quis sem laoreet nunc finibus eleifend sed ut augue. Donec luctus tortor ac nibh ultricies lobortis. Sed efficitur lacinia odio ut tincidunt. Nam et eleifend odio, in mattis nibh. Sed in mauris leo. Suspendisse consectetur sollicitudin quam quis varius. Nam feugiat sit amet enim ac eleifend.' +
    '\n' +
    'Vivamus hendrerit urna sit amet ex blandit, eget accumsan dui dignissim. Quisque ut leo et nisi lobortis pharetra a eu dolor. Nam nec neque blandit, semper arcu nec, mattis libero. Phasellus tempor eros in mi semper faucibus sed sit amet sem. Pellentesque egestas tellus a iaculis fermentum. Donec commodo non ipsum nec convallis. Mauris porta lectus ac sem ultrices, ut aliquam orci rhoncus. Sed scelerisque hendrerit purus lobortis elementum. Sed pulvinar et ipsum id viverra. Aliquam nibh massa, accumsan sed imperdiet a, iaculis nec sapien. In purus ex, euismod at eleifend in, dictum id orci. Maecenas eget pretium est. Phasellus ut tempor sem, non congue justo. Aliquam erat volutpat. Praesent condimentum rutrum ante sit amet accumsan. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.' +
    '\n' +
    'Curabitur sit amet quam sed odio fringilla hendrerit. Curabitur viverra nibh id nulla tristique rhoncus. Duis tempus facilisis ornare. Duis condimentum molestie finibus. Aliquam vestibulum quam non ante congue, eu ultrices erat dapibus. Suspendisse nulla arcu, rutrum et justo id, egestas consequat nibh. Suspendisse volutpat dignissim congue. Suspendisse hendrerit finibus lorem nec pellentesque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque ex elit, auctor at ullamcorper nec, commodo vitae sem. In id lobortis nibh, et venenatis libero.'
  )
}
