name: 'Auto Link Pull Request + Assign Author'

on:
  pull_request:
    types: [opened, labeled, reopened]

permissions:
  pull-requests: write

jobs:
  auto-link-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add pull request to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Master-Thesis-188199/projects/1
          github-token: ${{ secrets.GH_TOKEN }}

  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v2.1.1
