name: Build NextJS Application

on: push

jobs:
  build-nextjs-application:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

      NEXTAUTH_MONGODB_HOST_NAME: 'mongo'
      NEXTAUTH_MONGODB_PORT: 27017
      NEXTAUTH_MONGODB_DATABASE_NAME: ${{ secrets.NEXTAUTH_MONGODB_DATABASE_NAME }}

      NEXTAUTH_GITHUB_ID: ${{ secrets.NEXTAUTH_GITHUB_IDNEXTAUTH_GITHUB_ID }}
      NEXTAUTH_GITHUB_SECRET: ${{ secrets.NEXTAUTH_GITHUB_SECRET }}

      NEXTAUTH_GOOGLE_ID: ${{ secrets.NEXTAUTH_GOOGLE_ID }}
      NEXTAUTH_GOOGLE_SECRET: ${{ secrets.NEXTAUTH_GOOGLE_SECRET }}


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node 23.7
        uses: actions/setup-node@v3
        with:
          node-version: 23.7

      - name: Install dependencies
        run: yarn

      - name: Run Linting
        run: npm run lint

      - name: Run Build-Script
        run: npm run build