name: Run Tests

on: push

env:
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

  NEXTAUTH_MONGODB_HOST_NAME: 'mongo'
  NEXTAUTH_MONGODB_PORT: 27017
  NEXTAUTH_MONGODB_DATABASE_NAME: ${{ secrets.NEXTAUTH_MONGODB_DATABASE_NAME }}

  NEXTAUTH_GITHUB_ID: ${{ secrets.NEXTAUTH_GITHUB_ID}}
  NEXTAUTH_GITHUB_SECRET: ${{ secrets.NEXTAUTH_GITHUB_SECRET }}

  NEXTAUTH_GOOGLE_ID: ${{ secrets.NEXTAUTH_GOOGLE_ID }}
  NEXTAUTH_GOOGLE_SECRET: ${{ secrets.NEXTAUTH_GOOGLE_SECRET }}

jobs:
  run-all-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"  
          --health-interval 10s  
          --health-timeout 5s  
          --health-retries 5  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node 23.7
        uses: actions/setup-node@v3
        with:
          node-version: 23.7

      - name: Install Cypress Dependencies
        run: |
          sudo apt-get update  
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb  

      - name: Create Cypress Environment File
        run: |
          echo '{  
            "GOOGLE_USERNAME": "${{ secrets.TEST_GOOGLE_USERNAME }}",  
            "GOOGLE_PASSWORD": "${{ secrets.TEST_GOOGLE_PASSWORD }}",  
            "BASE_URL": "${{ secrets.NEXTAUTH_URL }}", 
            "SkipOnCi": true 
          }' > cypress.env.json      


      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run test:start-server
          browser: chrome

