name: Run Tests

on: push

jobs:
  run-all-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"  
          --health-interval 10s  
          --health-timeout 5s  
          --health-retries 5  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node 23.7
        uses: actions/setup-node@v3
        with:
          node-version: 23.7

      - name: Install Cypress Dependencies
        run: |
          sudo apt-get update  
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb  

      - name: Create Cypress Environment File
        run: |
          echo '{  
            "GOOGLE_USERNAME": "${{ secrets.TEST_GOOGLE_USERNAME }}",  
            "GOOGLE_PASSWORD": "${{ secrets.TEST_GOOGLE_PASSWORD }}",  
            "BASE_URL": "${{ secrets.NEXTAUTH_URL }}"  
          }' > cypress.env.json      


      - name: Install Dependencies
        run: yarn install

      - name: Run Test Script
        run: npm run test

